config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get '/about', to: 'home#about'

  get '/jobs', to: 'jobs#index'

  resources :posts, only: :show, param: :slug,path: 'post'

  namespace :dashboard do
    devise_for :users, only: [:sessions], path: ''

    resources :posts do
      member do
        post :publish
      end
      namespace :review do
        resources :comments, only: [:create]
      end
    end
    resources :users, only: [:new, :create, :edit, :update]
    resources :jobs, except: :destroy

    root 'panel#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates_presence_of :company, :description, :kind, :location, :link, :status

  enum status: [:pending_publish, :published, :pending_removal, :removed]
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, :slug, :lead, presence: true

  extend FriendlyId

  friendly_id :title, use: :slugged

  enum status: {
    draft: 'draft',
    review: 'review',
    approved: 'approved',
    published: 'published'
  }

  has_many :review_comments, class_name: 'Review::Comment'
  belongs_to :author, class_name: 'User'

  scope :new_published, -> { where(status: :published).reverse_order }

  before_create :set_header_image

  def publish!
    self.status = :published
    self.published_at = Time.current
    save!
  end

  private

  def set_header_image
    return if header_image.present?

    images = body.match(/((?:https|http)?:\/\/[\S]*.(?:jpg|jpeg|png))/)

    self.header_image = images[0] if images.present?
  end
end

app/models/review.rb
module Review
  def self.table_name_prefix
    'review_'
  end
end

app/models/review/comment.rb
class Review::Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_presence_of :user, :post, :body
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :review_comments, class_name: 'Review::Comment'
  has_many :posts

  has_one_attached :image_data

  validates_presence_of :full_name, :description, :quote
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :authenticate_dashboard_user!
  
  layout 'dashboard'
end

app/controllers/dashboard/jobs_controller.rb
class Dashboard::JobsController < Dashboard::BaseController
  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new(status: :published)
  end

  def edit
    @job = Job.find(params.require(:id))
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to dashboard_jobs_path
    else
      render :new
    end
  end

  def update
    @job = Job.find(params.require(:id))

    if @job.update(job_params)
      redirect_to dashboard_jobs_path
    else
      render :edit
    end
  end

  private

  def job_params
    params.require(:job).permit(
      :company, :description, :kind, :location, :link, :status
    )
  end
end

app/controllers/dashboard/panel_controller.rb
class Dashboard::PanelController < Dashboard::BaseController
  def index
  end
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < Dashboard::BaseController
  before_action :set_post, only: [:update, :destroy, :edit, :publish]

  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to dashboard_post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.includes(review_comments: [:user]).friendly.find(params[:id]).decorate
    @comments = @post.review_comments.decorate
    @new_comment = Review::Comment.new

    render layout: 'application'
  end

  def edit
  end

  def update
    @post.slug = nil

    if @post.update(post_params)
      redirect_to dashboard_post_path(@post)
    else
      render :edit
    end
  end

  def new
    @post = Post.new
  end

  def destroy
    @post.destroy
  end

  def publish
    @post.publish!

    redirect_to action: :index
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post)
          .permit([:title, :body, :lead, :status, :header_image])
          .merge(author: current_dashboard_user)
  end
end

app/controllers/dashboard/review/comments_controller.rb
class Dashboard::Review::CommentsController < Dashboard::BaseController
  layout 'application'

  def create
    @post = Post.friendly.find(params.fetch(:post_id))
    @new_comment = ::Review::Comment.new(comment_params(@post))

    if @new_comment.save
      redirect_to dashboard_post_path(@post)
    else
      @post = @post.decorate
      @comments = @post.review_comments.decorate

      render template: 'dashboard/posts/show'
    end
  end

  private

  def comment_params(post)
    params.require(:review_comment).permit(:body).merge(
      post: post,
      user: current_dashboard_user
    )
  end
end

app/controllers/dashboard/sessions_controller.rb
class Dashboard::SessionsController < ::Devise::SessionsController
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  before_action :set_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to dashboard_root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update user_params
      bypass_sign_in(@user)
      redirect_to dashboard_root_path
    else
      render :edit
    end
  end

  private

  def set_user
    @user ||= current_dashboard_user
  end

  def user_params
    params.require(:user).permit(
      [
        :image_data, :full_name, :quote, :description, :twitter, :github, :show,
        :linkedin, :password, :password_confirmation, :email
      ]
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
    @users = User.where(show: true).decorate
  end

  def index
    @posts = Post.includes(:author)
                 .page(current_page)
                 .per(current_per_page)
                 .new_published.decorate
    @next_page = next_page
    @previous_page = previous_page
  end

  private

  def current_per_page
    @current_per_page ||= params.fetch(:per_page, 10).to_i
  end

  def current_page
    @current_page ||= params.fetch(:page, 1).to_i
  end

  def next_page
    current_page + 1
  end

  def previous_page
    current_page - 1
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.where(status: [:published, :pending_removal])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.includes(:author).published.friendly.find(slug).decorate
  end

  private
  def slug
    params.require(:slug)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/comments/_index.html.erb
<% if comments.any? %>
  <ul class="comments">
    <% comments.each do |comment| %>
      <li class="comments__item">
        <%= render 'dashboard/comments/show', comment: comment %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="comments comments__item--none">
    Cobra review do pessoal :)
  </p>
<% end %>

app/views/dashboard/comments/_new.html.erb
<div class="comments">
  <%= form_for([:dashboard, :review, comment], url: dashboard_post_review_comments_path(post),
                                               html: {class: 'comments__item'}) do |form| %>
    <div class="comments__profile">
      <%= image_tag(current_dashboard_user.image_data { |image| url_for(image) }, class: 'comments__photo', alt: 'Author picture') %>
        <p>
          <%= current_dashboard_user.full_name %>
        </p>
    </div>

    <div class="comments__new">
      <%= form.text_area :body, class: 'comments__text-area', style: 'height: 60vh;' %>

      <%= form.submit class: 'comments__button' %>
    </div>

  <% end %>
</div>

app/views/dashboard/comments/_show.html.erb
<div class="comments__profile">
  <%= image_tag(comment.user.image_data { |image| url_for(image) }, class: 'comments__photo', alt: 'Author picture') %>
  <p>
    <%= comment.user.full_name %>
  </p>
</div>

<div class="post__body comments__body">
  <%= comment.body %>
</div>

app/views/dashboard/jobs/_form.html.erb
<div class="panel-body">
  <%= form_for [:dashboard, job], url: submit_url, method: method.to_s do |f| %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-4">
          <%= f.label :company %>
          <%= f.text_field :company, class: 'form-control' %>
        </div>

        <div class="col-md-4">
          <%= f.label :description %>
          <%= f.text_field :description, class: 'form-control' %>
        </div>

        <div class="col-md-4">
          <%= f.label :location %>
          <%= f.text_field :location, class: 'form-control' %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <%= f.label :kind %>
          <%= f.text_field :kind, class: 'form-control' %>
        </div>

        <div class="col-md-4">
          <%= f.label :status %>

          <%= f.select(:status, options_for_select(Job.statuses.keys, f.object.status), {}, {class: 'form-control'}) %>
        </div>

        <div class="col-md-4">
          <%= f.label :link %>
          <%= f.text_field :link, class: 'form-control' %>
        </div>
      </div>

    </div>

    <div class="row text-center">
      <%= f.submit 'Salvar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/dashboard/jobs/edit.html.erb
<div class="panel">
  <div class="panel-heading">
    Editar Vaga
  </div>

  <%= render 'form', job: @job,
                     submit_url: dashboard_job_path(@job),
                     method: :patch %>
</div>

app/views/dashboard/jobs/index.html.erb
<div class="panel">
  <div class="panel-heading">
    <h2>Vagas</h2>
  </div>

  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>Empresa</th>
          <th>Descrição</th>
          <th>Tipo</th>
          <th>Localização</th>
          <th>Link</th>
          <th>Status</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td><%= job.company %></td>
            <td><%= job.description %></td>
            <td><%= job.kind %></td>
            <td><%= job.location %></td>
            <td><%= job.link %></td>
            <td><%= job.status %></td>
            <td><%= link_to 'Editar', edit_dashboard_job_path(job) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboard/jobs/new.html.erb
<div class="panel">
  <div class="panel-heading">
    Nova Vaga
  </div>

  <%= render 'form', job: @job,
                     submit_url: dashboard_jobs_path,
                     method: :post %>
</div>

app/views/dashboard/panel/index.html.erb
<div class="panel">
  <div class="panel-heading">
    <h2>Dashboard</h2>
  </div>

  <div class="panel-body">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Posts
      </div>

      <div class="panel-body">
        <%= link_to('Posts', dashboard_posts_path, class: 'btn btn-default') %>

        <%= link_to('Criar Post', dashboard_post_path(:new), class: 'btn btn-default') %>
      </div>
    </div>

    <div class="panel panel-primary">
      <div class="panel-heading">
        Perfis
      </div>

      <div class="panel-body">
        <%= link_to('Editar Perfil', edit_dashboard_user_path(current_dashboard_user), class: 'btn btn-default')%>

        <%= link_to('Novo Perfil', new_dashboard_user_path, class: 'btn btn-default')%>
      </div>
    </div>

    <div class="panel panel-primary">
      <div class="panel-heading">
        Vagas
      </div>

      <div class="panel-body">
        <%= link_to('Todas as Vagas', dashboard_jobs_path, class: 'btn btn-default')%>

        <%= link_to('Nova Vaga', new_dashboard_job_path, class: 'btn btn-default')%>
      </div>
    </div>


    <div class="row">
      <div class="col-md-1 col-md-offset-11">
        <%= link_to('Sair', destroy_dashboard_user_session_path, method: :delete, class: 'btn btn-warning') %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/posts/_form.html.erb
<div class="panel-body">
  <%= form_with(model: [:dashboard, post], local: true) do |form| %>
    <div class="form-group">
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, id: :post_title, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= form.label :lead %>
        <%= form.text_field :lead, id: :post_lead, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= form.label :header_image %>
        <%= form.text_field :header_image, id: :post_header_image, class: 'form-control' %>
        <p class="help-block">Url completa ou 1ª imagem do post(automático). Não obrigatório.</p>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= form.label :body %>
        <%= form.text_area :body, id: :post_body, class: 'form-control', style: 'height: 60vh;' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/dashboard/posts/edit.html.erb
<div class="panel">
  <div class="panel-heading">
    <h2>Editar post</h2>
  </div>

  <%= render 'form', post: @post %>
</div>

app/views/dashboard/posts/index.html.erb
<div class="panel">
  <div class="panel-heading">
    <h2>Posts</h2>
  </div>

  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>Titulo</th>
          <th>Slug</th>
          <th>Lead</th>
          <th>Status</th>
          <th>Publicado em</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td><%= post.slug %></td>
            <td><%= post.lead %></td>
            <td>
              <% if post.published? %>
                <%= link_to 'published', post_path(post) %>
              <% else %>
                <%= post.status %>
              <% end %>
            </td>
            <td><%= post.published_at %></td>
            <td><%= link_to 'Visualizar', dashboard_post_path(post) %></td>
            <td><%= link_to 'Editar', edit_dashboard_post_path(post) %></td>
            <% unless post.published? %>
              <td><%= link_to 'Publicar', publish_dashboard_post_path(post), method: :post %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboard/posts/new.html.erb
<div class="panel">
  <div class="panel-heading">
    <h2>Novo post</h2>
  </div>

  <%= render 'form', post: @post %>
</div>

app/views/dashboard/posts/show.html.erb
<%= render "dashboard/shared/nav" %>

<div class="panel">
  <h1 style="text-align: center; margin: 10px;">[<%= @post.status.upcase %>]</h1>
  <article class="post">
    <%= render "posts/header", post: @post %>

    <%= render "posts/body", post: @post %>
  </article>

  <%= render "dashboard/comments/index", comments: @comments %>

  <%= render "dashboard/comments/new", comment: @new_comment, post: @post %>
</div>

app/views/dashboard/shared/_nav.html.erb
<nav class="shared-nav">
  <a href="/"><img class="shared-nav__logo" alt="Entrylvl logo" src="<%= asset_path 'entrylvl.svg'%>" /></a>
  <ul class="shared-nav__links">
    <li><%= link_to 'Dashboard', dashboard_root_path, class: 'shared-nav__link' %></li>
    <li><%= link_to 'Posts', dashboard_posts_path, class: 'shared-nav__link' %></li>
    <li><%= link_to('Sair', destroy_dashboard_user_session_path, method: :delete, class: 'shared-nav__link') %></li>
  </ul>
</nav>

app/views/home/_card.html.erb
<article class="card">
  <%= link_to post_path(post), class: 'card__link' do %>
    <%= content_tag :div, class: 'card__header', style: "background-image: url(#{post.header_image})" do %>
      <h2 class="card__title"><%= post.title %></h2>
    <% end %>

    <div class="card__footer">
      <div class="card__footer__text">
        <h3 class="card__footer__author"><%= post.author.full_name %></h3>
        <h4 class="card__footer__date"><%= post.published_at(date_only: true) %></h4>
      </div>

      <%= image_tag(post.author.image_data { |image| url_for(image) }, class: 'card__footer__picture', alt: 'Author picture') %>
    </div>
  <% end %>
</article>

app/views/home/about.html.erb
<%= render "shared/sharednav" %>
<div class="about">
  <header class="about__header">
    <h1 class="about__header__title"><em>wtf</em> is entry lvl?</h1>
  </header>
  <section class="about__tile">
    <div>
      <p class="about__tile__text">o <a class="link" href="/">entrylvl</a> existe pra mostrar o caminho das pedras pra quem quer iniciar ou está iniciando sua carreira.
      <p class="about__tile__text">a gente sabe bem das dificuldades de se ingressar na área de desenvolvimento de software.</p>
      <p class="about__tile__text">queremos te ajudar a conseguir seu primeiro emprego na área, aprender a desenvolver software e também a desenvolver-se como profissional.</p>
    </div>
  </section>
  <section class="about__authors">
    <h2 class="about__authors__title">Autores</h2>
    <ul class="about__authors__list">
      <% @users.each do |user| %>
        <li class="about__authors__author">
          <div class="about__authors__author__header">
            <div class="about__authors__author__avatar" style="background-image: url('<%= user.image_data { |image| url_for(image) } %>')"></div>
            <div>
              <h3 class="about__authors__author__name"><%= user.full_name %></h3>
              <h4 class="about__authors__author__work"><%= user.quote %></h4>
              <ul class="about__authors__author__links">
                <% if user.github.present? %>
                  <li><a class="about__authors__author__link" href="<%= user.github %>"><i class="fa fa-github"></i></a></li>
                <% end %>
                <% if user.linkedin.present? %>
                  <li><a class="about__authors__author__link" href="<%= user.linkedin %>"><i class="fa fa-linkedin"></i></a></li>
                <% end %>
                <% if user.twitter.present? %>
                  <li><a class="about__authors__author__link" href="<%= user.twitter %>"><i class="fa fa-twitter"></i></a></li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="about__authors__author__body">
            <p class="about__authors__author__intro"><%= user.description %></p>
          </div>
        </li>
      <% end %>
    </ul>
  </section>
</main>

app/views/home/index.html.erb
<%= render "shared/nav" %>
<div class="home">
  <main class="home__main">
    <% @posts.each do |post| %>
      <%= render "card", post: post %>
    <% end %>

    <div class="pagination">
      <% unless @previous_page.zero? %>
        <%= link_to '<<', root_path(page: @previous_page), class: 'pagination__link' %>
      <% end %>

      <%= @current_page %>

      <% if @posts.length == @current_per_page %>
        <%= link_to '>>', root_path(page: @next_page), class: 'pagination__link' %>
      <% end %>
    </div>
  </main>
</div>

app/views/home/post.html.erb
<%= render "shared/nav" %>

<article class="post">
  <header class="post__header">
    <h1 class="post__title">
      <%= @post.title %>
    </h1>
    <p class="post__subtitle">
      Descubra o desfecho dessa história
    </p>
    <ul class="card__tags">
      <li class="card__tag">tag a</li>
      <li class="card__tag">tag b</li>
    </ul>
  </header>
  <section class="post__body">
    <h2 class="post__body__subtitle">
      <%= @post.lead %>
    </h2>
    <%= @post.parsed_body do |body| %>
      <% body.gsub!(Regexp.new('<h2'), '<h2 class=\"post__body__subtitle\"') %>
      <% body.gsub!(Regexp.new('<p'), '<p class="post__body__text"') %>
    <% end.html_safe %>
  </section>

  <section class="post__footer">
      <div class="post__author__avatar"></div>
      <div class="post__author_info">
        <h3 class="post__author__name">Caique Mitsuoka</h3>
        <p class="post__author__intro">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
  </section>
</article>

<%= render "shared/footer" %>

app/views/jobs/index.html.erb
<%= render "shared/sharednav" %>
<header class="jobs__header">
  <h1 class="jobs__header__title">Mural de Vagas</h1>
  <nav class="jobs__header__actions">
    <a class="jobs__header__action" href="https://goo.gl/forms/TnZtEfl8vZGVrggS2" target="_blank">
      <p class="jobs__header__action__call">Anuncie uma Vaga</p>
      <p class="jobs__header__action__detail">encontre talentos promissores! 👷🏻‍♀‍</p>
    </a>
    <a class="jobs__header__action" href="#list">
      <p class="jobs__header__action__call">Consiga um Emprego</p>
      <p class="jobs__header__action__detail">olhe abaixo! 💰</p>
    </a>
  </nav>
</header>
<main class="jobs__body">
  <ul class="jobs__body__job-list" id="list">
    <% @jobs.each do |job|%>
      <li class="jobs__body__job">
        <%= link_to(job.link, class: 'jobs__body__job__link') do %>
          <div>
            <p class="jobs__body__job__company"><%= job.company %></p>
            <p class="jobs__body__job__position"><%= job.description %></p>
          </div>
          <div class="jobs__body__job__details">
            <p class="jobs__body__job__kind"><%= job.kind %></p>
            <p class="jobs__body__job__location"><%= job.location %></p>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>entry lvl</title>

    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>
  <body>
    <%= yield %>
    <%= render "shared/footer" %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-67803598-6"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-67803598-6');
    </script>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>entry lvl - dashboard</title>

    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
			  src="https://code.jquery.com/jquery-2.2.4.min.js"
			  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
			  crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "dashboard/shared/nav" %>

    <%= yield %>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/posts/_body.html.erb
<main class="post__body">
  <%= post.body %>
</main>

app/views/posts/_header.html.erb
<header class="post__header" style="background-image: url(<%= @post.header_image %>)">
  <h1 class="post__header__title">
    <%= post.title %>
  </h1>
  <ul class="post__header__taglist"></ul>
  <div class="post__header__info">
    <div class="post__header__info__text">
      <h2 class="post__header__info__author"><%= post.author.full_name %></h3>
      <h3 class="post__header__info__date"><%= post&.published_at(date_only: true) %></h3>
    </div>
    <%= image_tag(post.author.image_data  { |image| url_for(image) }, class: 'post__header__info__author-picture', alt: 'Author picture') %>
  </div>
</header>

app/views/posts/create.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Published at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.published_at %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/post.html.erb
<%= render "shared/sharednav" %>
<article class="post">
  <header class="post__header" style="background-image: url(<%= @post.header_image %>)">
    <h1 class="post__header__title">
      <%= @post.title %>
    </h1>
    <ul class="post__header__taglist"></ul>
    <div class="post__header__info">
      <div class="post__header__info__text">
        <h2 class="post__header__info__author"><%= @post.author.full_name %></h3>
        <h3 class="post__header__info__date"><%= @post.published_at(date_only: true) %></h3>
      </div>
      <%= image_tag(@post.author.image_data  { |image| url_for(image) }, class: 'post__header__info__author-picture', alt: 'Author picture') %>
    </div>
  </header>
  <main class="post__body">
    <%= @post.body %>
  </main>
  <section class="post__footer">
    <div class="post__footer__wrapper">
      <%= image_tag(@post.author.image_data { |image| url_for(image) }, class: 'post__author__avatar', alt: 'Author picture') %>
      <div class="post__author__info">
        <h3 class="post__author__name"><%= @post.author.full_name %></h3>
        <p class="post__author__intro"><%= @post.author.quote %></p>
      </div>
    </div>
    <div class="post__footer__comments">
      <div id="disqus_thread"></div>
      <script type="text/javascript">
        var disqus_config = function () {
          this.page.url = 'https://entrylvl.io/<%= @post.slug %>';
          this.page.identifier = '<%= @post.slug %>';
        };
        (function() {
        var d = document, s = d.createElement('script');
        s.src = 'https://entrylvl.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
      </script>
    </div>
  </section>
</article>
<script>hljs.initHighlightingOnLoad();</script>